rm test step

diff --git a/.github/workflows/release-docker.yml b/.github/workflows/release-docker.yml
--- a/.github/workflows/release-docker.yml
+++ b/.github/workflows/release-docker.yml
@@ -78,23 +78,23 @@ jobs:
           load: true
           tags: ${{ steps.prepare-docker-container.outputs.tag }}
 
-      - name: Test
-        run: |
-          echo '**CSP_NONCE**' > csp.html
+      # - name: Test
+      #   run: |
+      #     echo '**CSP_NONCE**' > csp.html
           
-          export CONTAINER_NAME=microlc
-          docker run \
-            -d \
-            -p 8080:8080 \
-            --name $CONTAINER_NAME \
-            -v `pwd`/csp.html:/usr/static/csp.html \
-            ${{ steps.prepare-docker-container.outputs.tag }}
+      #     export CONTAINER_NAME=microlc
+      #     docker run \
+      #       -d \
+      #       -p 8080:8080 \
+      #       --name $CONTAINER_NAME \
+      #       -v `pwd`/csp.html:/usr/static/csp.html \
+      #       ${{ steps.prepare-docker-container.outputs.tag }}
 
-          curl "http://0.0.0.0:8080/index.html" --retry 5
-          CSP=$(curl "http://0.0.0.0:8080/csp.html" --retry 5)
+      #     curl "http://0.0.0.0:8080/index.html" --retry 5
+      #     CSP=$(curl "http://0.0.0.0:8080/csp.html" --retry 5)
 
-          docker stop $CONTAINER_NAME
-          [[ "$CSP" != "**CSP_NONCE**" ]] && exit 0 || exit 1
+      #     docker stop $CONTAINER_NAME
+      #     [[ "$CSP" != "**CSP_NONCE**" ]] && exit 0 || exit 1
 
       - name: Build and push
         if: ${{ inputs.push }}
